"""initial_schema

Revision ID: 029257cbc9c4
Revises: 
Create Date: 2026-03-17 10:36:38.752474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029257cbc9c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_metrics_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('precision', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recall', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_decisions', sa.Integer(), nullable=True),
    sa.Column('correct_decisions', sa.Integer(), nullable=True),
    sa.Column('training_cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_weights',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.CheckConstraint("category IN ('tecnico', 'cultural', 'experiencia')", name='ck_ai_weights_category'),
    sa.CheckConstraint('weight >= 0 AND weight <= 100', name='ck_ai_weights_weight'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'recruiter', 'viewer')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('activo', 'inactivo')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidate_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=30), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.CheckConstraint("degree IN ('Bachiller','Tecnico','Tecnólogo','Pregrado','Especialización','Maestría','Doctorado')", name='ck_candidate_education_degree'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.CheckConstraint("level IN ('Básico', 'Intermedio', 'Avanzado', 'Nativo/Bilingüe')", name='ck_candidate_languages_level'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('date_posted', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('ref_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('activa', 'borrador', 'cerrada')", name='ck_jobs_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id')
    )
    op.create_index(op.f('ix_jobs_area'), 'jobs', ['area'], unique=False)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('ai_training_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ai_decision', sa.String(length=10), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('human_decision', sa.String(length=10), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint("ai_decision IN ('aprobado', 'rechazado', 'pendiente')", name='ck_training_ai_decision'),
    sa.CheckConstraint("human_decision IN ('aprobado', 'rechazado')", name='ck_training_human_decision'),
    sa.CheckConstraint('ai_score >= 0 AND ai_score <= 100', name='ck_training_ai_score'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_cases_candidate_id'), 'ai_training_cases', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ai_training_cases_job_id'), 'ai_training_cases', ['job_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('applied_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_decision', sa.String(length=10), nullable=False),
    sa.Column('human_decision', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("ai_decision IN ('aprobado', 'rechazado', 'pendiente')", name='ck_applications_ai_decision'),
    sa.CheckConstraint("human_decision IN ('nuevo', 'revisado', 'entrevista', 'aprobado', 'rechazado')", name='ck_applications_human_decision'),
    sa.CheckConstraint('ai_score >= 0 AND ai_score <= 100', name='ck_applications_ai_score'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_applications_candidate_job')
    )
    op.create_index(op.f('ix_applications_ai_score'), 'applications', ['ai_score'], unique=False)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('funcion', 'requisito', 'perfil_ideal')", name='ck_job_requirements_type'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_ai_score'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_ai_training_cases_job_id'), table_name='ai_training_cases')
    op.drop_index(op.f('ix_ai_training_cases_candidate_id'), table_name='ai_training_cases')
    op.drop_table('ai_training_cases')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_area'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('candidate_languages')
    op.drop_table('candidate_experience')
    op.drop_table('candidate_education')
    op.drop_table('users')
    op.drop_table('candidates')
    op.drop_table('ai_weights')
    op.drop_table('ai_metrics_history')
    # ### end Alembic commands ###
